# Generated by Django 5.0.3 on 2024-04-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('b', 'Bakalavr'), ('m', 'Magistr'), ('d', 'phd')], default='b', max_length=20),
        ),
    ]
